# ZÁKLADNÍ KONFIGURACE WEBU
title: JAM Stack
email: jakubminka@gmail.com
description:
  Tvorba webu s využitím technologie JAM Stack
  # Praktická část bakalářské práce studenta katedry informatiky Pedagogické fakulty
  # Jihočeské univerzity v Českých Budějovicích Jakuba Minky na téma moderní technologie
  # pro vývoj webu JAM Stack
baseurl: ""
url: "https://zen-torvalds-384b19.netlify.com/"
github_username: jakubminka
footer: JAM Stack

# NASTAVENÍ BUILDU A DALŠÍ OBECNÁ NASTAVENÍ
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

permalink: pretty
sass:
  sass_dir: _sass

# DEFINICE GLOBÁLNÍCH PROMĚNNÝCH
color:
  primary-dark: "#000000"
  links: "#219ab3"
  background: "f8f8ff"
  myBlue: "#42bcf4"

# ALGOLIA NASTAVENÍ
algolia:
  application_id: PDMQTM8G33
  index_name: PDMQTM8G33
  search_only_api_key: 4fbd50b80279fa3a1bb80d6c0f24472a

# Kolekce eshopu
collections:
  products:
    output: true

snipcart:
  api_key: MmEwYTM4NzQtNDk4Ni00ODlkLWIyZTktNWQ0MjA0NWIxYWI5NjM2ODYyNzk5NDk4OTMzNTQz
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
