# ZÁKLADNÍ KONFIGURACE WEBU
title: JAM Stack
email: jakubminka@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Praktická část bakalářské práce studenta katedry informatiky Pedagogické fakulty
  Jihočeské univerzity v Českých Budějovicích Jakuba Minky na téma moderní technologie
  pro vývoj webu JAM Stack
baseurl: ""
url: "https://zen-torvalds-384b19.netlify.com"
github_username: jakubminka
footer: JAM Stack

# NASTAVENÍ BUILDU A DALŠÍ OBECNÁ NASTAVENÍ
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

permalink: pretty
sass:
  sass_dir: _sass

# DEFINICE GLOBÁLNÍCH PROMĚNNÝCH
color:
  primary-dark: "#000000"
  links: "#219ab3"
  background: "f8f8ff"

# ALGOLIA NASTAVENÍ
algolia:
  application_id: "PDMQTM8G33"

# PAGINATE PLUGIN
paginate: 5
# paginate_path: "/posts/page:num/"
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
