backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow

media_folder: "images/uploads"

collections:
  - name: "prispevek"
    label: "Příspěvek"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "Název", name: "title", widget: "string" }
      - { label: "Popis", name: "excerpt", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Datum publikování", name: "date", widget: "datetime" }
      - { label: "Ilustrační obrázek", name: "thumbnail", widget: "image" }
      - { label: "Kategorie", name: "categories", widget: "string" }
      - { label: "Komenty", name: "comments", widget: "boolean" }
      - { label: "Text", name: "body", widget: "markdown" }
  - name: "produkt"
    label: "Produkt"
    folder: "_products"
    create: true
    fields:
      - {
          label: "Layout",
          name: "layout",
          widget: "hidden",
          default: "detailProduktu",
        }
      - { label: "Název", name: "name", widget: "string" }
      - { label: "Cena", name: "price", widget: "number" }
      - { label: "Obrázek", name: "image", widget: "image" }
      - { label: "Kategorie", name: "category", widget: "string" }
